
# taking example 1 from https://github.com/patrickdlee/vagrant-examples
Vagrant.configure("2") do |config|
  
  config.vm.box = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'

  config.vm.network "public_network"
end
