
# taking example 1 from https://github.com/patrickdlee/vagrant-examples
Vagrant::Config.run do |config|
  config.vm.box = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'
end
