
# taking example 1 from https://github.com/patrickdlee/vagrant-examples
Vagrant.configure("2") do |config|
  
  config.vm.box = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'

  config.vm.network :forwarded_port,
    guest: 22,
    host: 2200,
    id: "ssh",
    auto_correct: true
  config.vm.network :private_network, type: :dhcp
end
